using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YGZFrameWork.SourceGenerator
{
    /// <summary>
    /// Source Generator：编译时自动扫描所有 CfgToolBase&lt;TKey, TData&gt; 子类，
    /// 生成 CfgToolRegistry.TouchAllInstances()，零反射、零运行时开销。
    /// 微信小游戏 / IL2CPP 完全兼容。
    /// </summary>
    [Generator]
    public class CfgToolSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // 无需初始化
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var compilation = context.Compilation;

            // 查找 CfgToolBase<TKey, TData> 的符号（开放泛型）
            var cfgToolBaseSymbol = compilation.GetTypeByMetadataName("YGZFrameWork.CfgToolBase`2");
            if (cfgToolBaseSymbol == null)
            {
                // 如果基类还没编译到，跳过本次生成（增量编译时会再次触发）
                return;
            }

            var cfgToolClasses = new List<(string FullTypeName, string InstanceProperty)>();

            foreach (var tree in compilation.SyntaxTrees)
            {
                // 跳过 Source Generator 自身生成的代码，避免循环
                if (tree.FilePath != null && tree.FilePath.EndsWith(".g.cs"))
                    continue;

                var semanticModel = compilation.GetSemanticModel(tree);
                var root = tree.GetRoot();

                var classDeclarations = root.DescendantNodes()
                    .OfType<ClassDeclarationSyntax>()
                    .Where(c => c.BaseList != null);

                foreach (var classDecl in classDeclarations)
                {
                    var symbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (symbol == null) continue;

                    // 跳过抽象类（不能实例化）
                    if (symbol.IsAbstract) continue;

                    // 检查是否继承 CfgToolBase<TKey, TData>
                    if (!IsDerivedFromCfgToolBase(symbol, cfgToolBaseSymbol))
                        continue;

                    // 查找静态单例属性：优先 mInstance，其次 Instance
                    var instanceProp = symbol.GetMembers()
                        .OfType<IPropertySymbol>()
                        .FirstOrDefault(p => p.IsStatic &&
                            (p.Name == "mInstance" || p.Name == "Instance"));

                    if (instanceProp == null)
                        continue;

                    string fullName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
                        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                    cfgToolClasses.Add((fullName, instanceProp.Name));
                }
            }

            var source = GenerateRegistrySource(cfgToolClasses);
            context.AddSource("CfgToolRegistry.g.cs", source);
        }

        /// <summary>
        /// 递归检查 symbol 是否继承自 CfgToolBase&lt;,&gt;
        /// </summary>
        private bool IsDerivedFromCfgToolBase(INamedTypeSymbol symbol, INamedTypeSymbol baseSymbol)
        {
            var current = symbol.BaseType;
            while (current != null)
            {
                // 比较开放泛型定义（忽略具体泛型参数）
                if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, baseSymbol))
                    return true;
                current = current.BaseType;
            }
            return false;
        }

        private string GenerateRegistrySource(List<(string FullTypeName, string InstanceProperty)> classes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by YGZFrameWork.CfgTool.SourceGenerator");
            sb.AppendLine("// 任何手动修改都会被下次编译覆盖");
            sb.AppendLine();
            sb.AppendLine("namespace YGZFrameWork");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 编译时自动生成的配置表注册中心");
            sb.AppendLine("    /// 新增配置表只需创建 CfgToolBase&lt;TKey,TData&gt; 子类，零改现有代码");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class CfgToolRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 访问所有配置表单例，触发懒加载和向 CfgToolManager 自动注册");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void TouchAllInstances()");
            sb.AppendLine("        {");

            foreach (var (fullName, propName) in classes)
            {
                // 去掉 namespace 前缀，假设都在 YGZFrameWork 下
                var shortName = fullName.Contains(".")
                    ? fullName.Substring(fullName.LastIndexOf('.') + 1)
                    : fullName;

                sb.AppendLine($"            _ = {shortName}.{propName};");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
